=== NousPratIT/Maximo-Wind/maximo/referenceapp/resources/registry-extensions/control-registry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
* Licensed Materials - Property of IBM
* Restricted Materials of IBM
* 5724-U18
* (C) COPYRIGHT IBM CORP. 2010 All Rights Reserved.
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with
* IBM Corp.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:include schemaLocation="components.xsd" />
	
<!--	<xsd:complexType name="componentListType">-->
<!--		<xsd:choice>-->
<!--			<xsd:any maxOccurs="unbounded" processContents="lax"/>-->
<!--		</xsd:choice>-->
<!--	</xsd:complexType>-->

	<xsd:element name="control-registry">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="control-descriptor" />
			</xsd:sequence>
			<xsd:attribute name="package" type="xsd:string" />
			<xsd:attribute name="basedir" type="xsd:string" />
		</xsd:complexType>
		<xsd:unique name="control-descriptor-name-uniqueness">
			<xsd:selector xpath="control-descriptor"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>

	<xsd:element name="control-descriptor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property-list" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="component-list" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="containers" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="bindlist" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="template" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="instance-class" type="xsd:string" />
			<xsd:attribute name="descriptor-class" type="xsd:string" />
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="controltype" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="property-list">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="property" />
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="property-name-uniqueness">
			<xsd:selector xpath="property"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="property">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="flag" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="default-value" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="value" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="type" type="xsd:QName" default="xsd:string"/>
		</xsd:complexType>
		<xsd:unique name="flag-name-uniqueness">
			<xsd:selector xpath="flag"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="flag">
		<xsd:complexType>
			<xsd:attribute name="name" type="flag" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="flag">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="global"></xsd:enumeration>
			<xsd:enumeration value="system"></xsd:enumeration>
			<xsd:enumeration value="final"></xsd:enumeration>
			<xsd:enumeration value="translatable"></xsd:enumeration>
			<xsd:enumeration value="nonconditional"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="default-value" type="xsd:string" />
	<xsd:element name="value">
		<xsd:complexType mixed="true">
			<xsd:attribute name="default" type="xsd:boolean"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="component-list" type="componentListType" />

	<xsd:element name="containers">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="container" />
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="container-name-uniqueness">
			<xsd:selector xpath="container"/>
			<xsd:field    xpath="@name"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="container">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="bindlist">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element maxOccurs="unbounded" ref="attribute" />
			</xsd:sequence>
		</xsd:complexType>
		<xsd:unique name="attribute-uniqueness">
			<xsd:selector xpath="attribute"/>
			<xsd:field    xpath="@property"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="attribute">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="label" minOccurs="0">
					<xsd:complexType>
						<xsd:attribute name="property" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element ref="inputmode" />
			</xsd:sequence>
			<xsd:attribute name="property" type="xsd:string" use="required" />
		</xsd:complexType>
		<xsd:unique name="inputmode-uniqueness">
			<xsd:selector xpath="inputmode"/>
			<xsd:field    xpath="@property"/>
		</xsd:unique>
		<xsd:unique name="label-uniqueness">
			<xsd:selector xpath="label"/>
			<xsd:field    xpath="@property"/>
		</xsd:unique>
	</xsd:element>
	<xsd:element name="inputmode">
		<xsd:complexType>
			<xsd:attribute name="property" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="template">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:any minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== NousPratIT/Maximo-Wind/maximo/referenceapp/resources/registry-extensions/refapp-control-registry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
* Licensed Materials - Property of IBM
* Restricted Materials of IBM
* 5724-U18
* (C) COPYRIGHT IBM CORP. 2011 All Rights Reserved.
* US Government Users Restricted Rights - Use, duplication or
* disclosure restricted by GSA ADP Schedule Contract with
* IBM Corp.
-->
<control-registry basedir="webclient\controls" package="psdi.refapp.controls"
		xsi:noNamespaceSchemaLocation='control-registry.xsd'
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<control-descriptor name="refbutton">
		<property-list>
			<property name="display" type="xsd:boolean">
				<flag name="global" />
				<default-value>true</default-value>
			</property>
			<property name="id">
				<flag name="final" />
			</property>
			<property name="refbuttontype" />
		</property-list>
		<component-list>
			<components id="${name}_comps1" layout="vertical">
				<components id="${name}_comps2" layout="horizontal" valign="middle">
					<refbutton id="${name}_refbutton" refbuttontype="@{refbuttontype}"/>
				</components>
			</components>
		</component-list>
		<containers>
			<container name="buttongroup" />
			<container name="section" />
			<container name="sectioncol" />
		</containers>
	</control-descriptor>

	<control-descriptor name="iwidget">
		<property-list>
			<property name="id">
				<flag name="final" />
			</property>
			<property name="display" type="xsd:boolean">
				<flag name="global" />
				<default-value>true</default-value>
			</property>
			<property name="name" />
			<property name="textcss">
				<flag name="global" />
				<flag name="final" />
				<default-value>text</default-value>
			</property>
			<property name="width" />
			<property name="height" />
			<property name="href" />
			<property name="islocal" type="xsd:boolean">
				<default-value>true</default-value>
			</property>
		</property-list>
		<component-list>
			<components id="${name}_components_h" layout="horizontal" nowrap="true">
				<iframe id="${name}_iframe" scroll="no" height="@{height}" width="@{width}" src="/webclient/components/refapp/iwidget.jsp" textcss="@{textcss}" />
			</components>
		</component-list>
		<containers>
			<container name="tab" />
			<container name="section" />
			<container name="sectioncol" />
			<container name="dialog" />
			<container name="clientarea" />
			<container name="page" />
		</containers>
	</control-descriptor>

	<control-descriptor name="stockiwidget">
		<property-list>
			<property name="id">
				<flag name="final" />
			</property>
			<property name="display" type="xsd:boolean">
				<flag name="global" />
				<default-value>true</default-value>
			</property>
			<property name="name" />
			<property name="textcss">
				<flag name="global" />
				<flag name="final" />
				<default-value>text</default-value>
			</property>
			<property name="width" />
			<property name="height" />
			<property name="number" />
		</property-list>
		<component-list>
			<components id="${name}_components_h" layout="horizontal" nowrap="true">
				<iframe id="${name}_iframe" scroll="no" height="@{height}" width="@{width}" src="/webclient/components/refapp/stockiwidget.jsp" textcss="@{textcss}" />
			</components>
		</component-list>
		<containers>
			<container name="tab" />
			<container name="section" />
			<container name="sectioncol" />
			<container name="dialog" />
			<container name="clientarea" />
			<container name="page" />
		</containers>
	</control-descriptor>
	
	<control-descriptor name="dojo-sample-dialog">
		<property-list>
			<property name="id">
				<flag name="final" />
			</property>
		</property-list>
		<component-list>
			<components id="${name}_comps1" layout="vertical">
				<components id="${name}_comps2" layout="horizontal" valign="middle">
					<dojo-sample-dialog id="${name}" />
				</components>
			</components>
		</component-list>
		<containers>
			<container name="tab" />
			<container name="section" />
			<container name="sectioncol" />
			<container name="dialog" />
			<container name="clientarea" />
			<container name="page" />
		</containers>
	</control-descriptor>

	<control-descriptor name="dojo-sample-dialogcreateonshow">
		<property-list>
			<property name="id">
				<flag name="final" />
			</property>
		</property-list>
		<component-list>
			<components id="${name}_comps1" layout="vertical">
				<components id="${name}_comps2" layout="horizontal" valign="middle">
					<dojo-sample-dialogcreateonshow id="${name}" />
				</components>
			</components>
		</component-list>
		<containers>
			<container name="tab" />
			<container name="section" />
			<container name="sectioncol" />
			<container name="dialog" />
			<container name="clientarea" />
			<container name="page" />
		</containers>
	</control-descriptor>

	<control-descriptor name="dojo-sample-button">
		<property-list>
			<property name="id">
				<flag name="final" />
			</property>
		</property-list>
		<component-list>
			<components id="${name}_comps1" layout="vertical">
				<components id="${name}_comps2" layout="horizontal" valign="middle">
					<dojo-sample-button id="${name}" />
				</components>
			</components>
		</component-list>
		<containers>
			<container name="tab" />
			<container name="section" />
			<container name="sectioncol" />
			<container name="dialog" />
			<container name="clientarea" />
			<container name="page" />
		</containers>
	</control-descriptor>

	<control-descriptor name="dojo-sample-slider">
		<property-list>
			<property name="id">
				<flag name="final" />
			</property>
			<property name="dataattribute">
				<flag name="final" />
			</property>
			<property name="datasrc">
				<flag name="nonconditional" />
				<flag name="global" />
			</property>
			<property name="hidelabel" type="xsd:boolean">
				<default-value>false</default-value>
			</property>
			<property name="label">
				<flag name="translatable" />
			</property>
			<property name="synchronous" type="xsd:boolean">
				<flag name="final" />
				<default-value>false</default-value>
			</property>
			<property name="inputmode">
				<flag name="global" />
			</property>

			<property name="minimum" type="xsd:integer">
				<default-value>0</default-value>
			</property>
			<property name="maximum" type="xsd:positiveInteger">
				<default-value>100</default-value>
			</property>
			<property name="increment" type="xsd:positiveInteger">
				<default-value>1</default-value>
			</property>
			<property name="labelincrement" type="xsd:positiveInteger">
				<default-value>10</default-value>
			</property>

		</property-list>
		<component-list>
			<components id="${name}_comps1" layout="vertical">
				<components id="${name}_comps2" layout="horizontal" valign="middle">
					<label id="${name}_label" dataattribute="@{dataattribute}" inputmode="@{inputmode}" title="@{label}"
						align="right" hidelabel="@{hidelabel}" ignoredatachange="true" labelfor="${name}_richtextviewer" />
					<dojo-sample-slider id="${name}" dataattribute="@{dataattribute}" synchronous="@{synchronous}" inputmode="@{inputmode}" 
						minimum="@{minimum}" maximum="@{maximum}" increment="@{increment}" labelincrement="@{labelincrement}"/>
				</components>
			</components>
		</component-list>
		<containers>
			<container name="tab" />
			<container name="section" />
			<container name="sectioncol" />
			<container name="dialog" />
			<container name="clientarea" />
			<container name="page" />
		</containers>
		<template>
			<dojo-sample-slider id="ctrl_dojo-sample-slider"/>
		</template>
	</control-descriptor>
	
</control-registry>
